
name: Madina Dates

on:
  push:
    branches: [ master ]
 
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
      
    - name: Installing NodeJS
      uses: actions/steup-node@v2-beta
      with:
        node-version: 12
      
    - name: Installing surge 
      run: npm install --global surge
      
    - name: deploying using surge
      run:  surge ./ madinadates.surge.sh --token $ {{ secrects.MADINA_DATETOKEN }}
    
    
