
name: Madina Dates

on:
  push:
    branches: [ master ]
 
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2-beta
      
      
    - name: Installing NodeJS
      uses: actions/setup-node@v1.4.2
      with:
        node-version: 12
      
    - name: Installing surge 
      run: npm install --global surge
      
    - name: deploying using surge
      run:  surge ./ madinadates/surge-sh-action@v1.0.0 --token $ {{ secrects.MADINA_DATETOKEN }}
    
    
